apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["ping"]
    args: ["10.26.0.3"]
  restartPolicy: OnFailure

