apiVersion: v1
kind: Service
metadata:
  name: doccano-ui
spec:
  selector:
    app: doccano
  ports:
    - protocol: TCP
      port: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doccano
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doccano
  template:
    metadata:
      labels:
        app: doccano
    spec:
      containers:
        - name: doccano
          image: chakkiworks/doccano
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: postgres://test-username:sQdMglkg43F456y865i43@10.26.0.3:5432/test-db?sslmode=disable
---
apiVersion: v1
kind: Pod
metadata:
  name: command-demo2
  labels:
    purpose: demonstrate-command2
spec:
  containers:
  - name: command-demo-container2
    image: debian
    command: ["ping"]
    args: ["10.26.0.3"]
  restartPolicy: OnFailure
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress
spec:
  backend:
    serviceName: doccano-ui
    servicePort: 8000
#  rules:
#    - http:
#        paths:
#          - path: /nlp-api/*
#            backend:
#              serviceName: nlp-demo-backend
#              servicePort: 8001
